// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as ClerkReact from "@clerk/clerk-react";

function App(props) {
  var useUser = ClerkReact.useUser();
  var user = useUser.user;
  var name;
  if (user == null) {
    name = null;
  } else {
    var name$1 = user.fullName;
    name = name$1 !== undefined ? JsxRuntime.jsx("h1", {
            children: "Hello, " + name$1
          }) : null;
  }
  return JsxRuntime.jsxs("header", {
              children: [
                name,
                JsxRuntime.jsx(ClerkReact.SignedOut, {
                      children: JsxRuntime.jsx(ClerkReact.SignInButton, {
                            children: "Sign in"
                          })
                    }),
                JsxRuntime.jsx(ClerkReact.SignedIn, {
                      children: JsxRuntime.jsx(ClerkReact.SignOutButton, {
                            children: "Sign out"
                          })
                    })
              ]
            });
}

var make = App;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
