// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.mjs";
import * as React from "react";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";
import * as ClerkReact from "@clerk/clerk-react";

import './index.css'
;

var domElement = document.querySelector("#root");

if (!(domElement == null)) {
  Client.createRoot(domElement).render(JsxRuntime.jsx(React.StrictMode, {
            children: JsxRuntime.jsx(ClerkReact.ClerkProvider, {
                  publishableKey: import.meta.env.VITE_CLERK_PUBLISHABLE_KEY,
                  children: JsxRuntime.jsx(App.make, {})
                })
          }));
}

export {
  
}
/*  Not a pure module */
